-- ========================================================
-- SCRIPT DE RESTAURACIÓN MAESTRO - PORTAL CAUTIVO
-- ========================================================
-- Este script recrea la estructura completa, disparadores y políticas RLS.
-- Ejecútalo en el SQL Editor de Supabase.

-- 0. Limpieza (Opcional - Úsalo si quieres empezar de cero)
-- DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
-- DROP FUNCTION IF EXISTS public.handle_new_user();
-- DROP TABLE IF EXISTS payment_history;
-- DROP TABLE IF EXISTS messages;
-- DROP TABLE IF EXISTS profiles;

-- Habilitar extensión UUID
create extension if not exists "uuid-ossp";

-- 1. TABLA DE PERFILES
create table if not exists profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text,
  role text default 'resident',
  payment_status text default 'pending', -- paid, pending, overdue
  next_payment_date text,
  internet_speed int default 20,
  wifi_ssid text,
  wifi_pass text,
  alias text
);

-- 2. TABLA DE MENSAJES
create table if not exists messages (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  text text not null,
  sender_role text not null, -- 'admin' or 'resident'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  read boolean default false
);

-- 3. TABLA DE HISTORIAL DE PAGOS
create table if not exists payment_history (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  period text,
  amount text,
  status text,
  date text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Habilitar RLS
alter table profiles enable row level security;
alter table messages enable row level security;
alter table payment_history enable row level security;

-- 5. POLÍTICAS DE SEGURIDAD (RLS)

-- PROFILES
create policy "Users can view own profile" on profiles for select using (auth.uid() = id);
create policy "Authenticated users can view profiles" on profiles for select using (auth.role() = 'authenticated');
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);
create policy "Admins can update any profile" on profiles for update using (
  auth.uid() IN (SELECT id FROM profiles WHERE role = 'admin')
);
create policy "Admins can delete profiles" on profiles for delete using (
  auth.uid() IN (SELECT id FROM profiles WHERE role = 'admin')
);
create policy "Users can insert their own profile" on profiles for insert with check (auth.uid() = id);

-- MESSAGES
create policy "Users can view own messages" on messages for select using (auth.uid() = user_id);
create policy "Users can insert own messages" on messages for insert with check (auth.uid() = user_id);
create policy "Admins can insert messages to any user" on messages for insert with check (
  auth.uid() IN (SELECT id FROM profiles WHERE role = 'admin')
);
create policy "Admins can delete messages" on messages for delete using (
  auth.uid() IN (SELECT id FROM profiles WHERE role = 'admin')
);

-- PAYMENT_HISTORY
create policy "View own payment history" on payment_history for select using (auth.uid() = user_id);
create policy "Admins can full control history" on payment_history
  for all using (auth.uid() IN (SELECT id FROM profiles WHERE role = 'admin'));

-- 6. FUNCIÓN Y TRIGGER PARA NUEVOS USUARIOS
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, role)
  values (new.id, new.raw_user_meta_data->>'username', coalesce(new.raw_user_meta_data->>'role', 'resident'));
  return new;
end;
$$ language plpgsql security definer;

-- Borrar trigger si ya existe para evitar errores
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ========================================================
-- INSTRUCCIONES:
-- 1. Copia y pega este código en el SQL Editor de Supabase.
-- 2. Presiona RUN.
-- 3. Si borraste los usuarios de Auth, deberán registrarse de nuevo.
-- 4. Si los usuarios de Auth aún existen, podrán loguearse y sus perfiles
--    se recuperarán gracias a la política de INSERT en profiles.
-- ========================================================
