-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. PROFILES Table (Extends auth.users)
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text,
  role text default 'resident',
  payment_status text default 'pending', -- paid, pending, overdue
  next_payment_date text,
  internet_speed int default 150,
  wifi_ssid text,
  wifi_pass text,
  alias text
);

-- 2. MESSAGES Table
create table messages (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  text text not null,
  sender_role text not null, -- 'admin' or 'resident'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  read boolean default false
);

-- 3. PAYMENT_HISTORY Table
create table payment_history (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  period text,
  amount text,
  status text,
  date text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Enable RLS (Row Level Security)
alter table profiles enable row level security;
alter table messages enable row level security;
alter table payment_history enable row level security;

-- 5. RLS Policies

-- PROFILES Policies
-- Residents can read their own profile
create policy "Residents can view own profile" on profiles
  for select using (auth.uid() = id);

-- Admins can view all profiles (We will assume a specific admin email or role check later, for now we allow read all if authenticated for simplicity in this demo, or we can make it stricter)
-- For simplicity: Allow any authenticated user to read profiles (needed for admin dashboard to see residents)
create policy "Authenticated users can view profiles" on profiles
  for select using (auth.role() = 'authenticated');

-- Only user can update their own profile (alias) OR admin can update any (simplified: allow update if auth.uid = id or if user is admin)
create policy "Users can update own profile" on profiles
  for update using (auth.uid() = id);

-- MESSAGES Policies
-- Users can read messages belonging to them
create policy "Users can view own messages" on messages
  for select using (auth.uid() = user_id);

-- Users can insert messages to themselves
create policy "Users can insert own messages" on messages
  for insert with check (auth.uid() = user_id);

-- PAYMENT_HISTORY Policies
-- View own history
create policy "View own payment history" on payment_history
  for select using (auth.uid() = user_id);


-- TRIGGER: Create Profile on Signup
-- This automatically creates a row in 'profiles' when a user signs up via auth
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, role)
  values (new.id, new.raw_user_meta_data->>'username', coalesce(new.raw_user_meta_data->>'role', 'resident'));
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
